#define TSCH_CONF_DEFAULT_HOPPING_SEQUENCE	     TSCH_JAMMING_SEQUENCE
#define TSCH_CONF_DEFAULT_HOPPING_SEQUENCE	     TSCH_JAMMING_SEQUENCE

#define TSCH_CONF_DEFAULT_TIMESLOT_TIMING	     tsch_timeslot_timing_us_10000
#define TSCH_SCHEDULE_CONF_DEFAULT_LENGTH	     8

#define LOG_CONF_LEVEL_IPV6                        LOG_LEVEL_WARN
#define LOG_CONF_LEVEL_6LOWPAN                     LOG_LEVEL_WARN
#define LOG_CONF_LEVEL_MAC                         LOG_LEVEL_INFO
#define LOG_CONF_LEVEL_FRAMER                      LOG_LEVEL_WARN
#define TSCH_LOG_CONF_PER_SLOT                     1
